// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPPoO0PZhqPyGXG1RJ7ULqtHUqNesVMEU',
    appId: '1:668252268450:web:9d04234dec5e27cf50f4fb',
    messagingSenderId: '668252268450',
    projectId: 'buzzer-f8cd2',
    authDomain: 'buzzer-f8cd2.firebaseapp.com',
    storageBucket: 'buzzer-f8cd2.appspot.com',
    measurementId: 'G-VJMJF717S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz1cyaXV_gbslzOfD2fpTQTZFUrX4vEm8',
    appId: '1:668252268450:android:7953dfb5f554da0f50f4fb',
    messagingSenderId: '668252268450',
    projectId: 'buzzer-f8cd2',
    storageBucket: 'buzzer-f8cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4ftO43xrU4Z9NPVT8Z9wJZ81LOPWrHM',
    appId: '1:668252268450:ios:658f3b017c4e888450f4fb',
    messagingSenderId: '668252268450',
    projectId: 'buzzer-f8cd2',
    storageBucket: 'buzzer-f8cd2.appspot.com',
    iosBundleId: 'com.example.buzzer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE4ftO43xrU4Z9NPVT8Z9wJZ81LOPWrHM',
    appId: '1:668252268450:ios:658f3b017c4e888450f4fb',
    messagingSenderId: '668252268450',
    projectId: 'buzzer-f8cd2',
    storageBucket: 'buzzer-f8cd2.appspot.com',
    iosBundleId: 'com.example.buzzer2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPPoO0PZhqPyGXG1RJ7ULqtHUqNesVMEU',
    appId: '1:668252268450:web:2a26f6e2b5d2da5e50f4fb',
    messagingSenderId: '668252268450',
    projectId: 'buzzer-f8cd2',
    authDomain: 'buzzer-f8cd2.firebaseapp.com',
    storageBucket: 'buzzer-f8cd2.appspot.com',
    measurementId: 'G-5R5NSVNVLG',
  );
}
